import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';

const geistUbuntu = Ubuntu({
    variable: '--font-ubuntu',
    subsets: ['latin'],
    weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistUbuntu.variable}`}>
                <header className="header">
                    <Header />
                </header>
                <main>{children}</main>
            </body>
        </html>
    );
}
